################################################################################
# Copyright (c) 1991, 2017 IBM Corp. and others
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which accompanies this
# distribution and is available at https://www.eclipse.org/legal/epl-2.0/
# or the Apache License, Version 2.0 which accompanies this distribution and
# is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# This Source Code may also be made available under the following
# Secondary Licenses when the conditions for such availability set
# forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
# General Public License, version 2 with the GNU Classpath
# Exception [1] and GNU General Public License, version 2 with the
# OpenJDK Assembly Exception [2].
#
# [1] https://www.gnu.org/software/classpath/license.html
# [2] http://openjdk.java.net/legal/assembly-exception.html
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
################################################################################

set(OMR_OPT_CUDA OFF CACHE BOOL "")


set(OMR_GC_COMPRESSED_POINTERS ON CACHE BOOL "")
set(OMR_GC_DYNAMIC_CLASS_UNLOADING ON CACHE BOOL "")
set(OMR_GC_HYBRID_ARRAYLETS ON CACHE BOOL "")
set(OMR_GC_IDLE_HEAP_MANAGER ON CACHE BOOL "")
set(OMR_GC_LEAF_BITS ON CACHE BOOL "")
set(OMR_GC_MODRON_COMPACTION ON CACHE BOOL "")
set(OMR_GC_MODRON_CONCURRENT_MARK ON CACHE BOOL "")
set(OMR_GC_MODRON_SCAVENGER ON CACHE BOOL "")
set(OMR_GC_REALTIME ON CACHE BOOL "")
set(OMR_GC_SEGREGATED_HEAP ON CACHE BOOL "")
set(OMR_GC_STACCATO ON CACHE BOOL "")
set(OMR_GC_TLH_PREFETCH_FTA ON CACHE BOOL "")
set(OMR_GC_VLHGC ON CACHE BOOL "")

set(OMR_INTERP_COMPRESSED_OBJECT_HEADER ON CACHE BOOL "")
set(OMR_INTERP_SMALL_MONITOR_SLOT ON CACHE BOOL "")

set(J9VM_PORT_RUNTIME_INSTRUMENTATION OFF CACHE BOOL "")

#TODO these options to be properly configured like the rest
set(OMR_GC_ARRAYLETS ON CACHE BOOL "")
set(OMR_GC_CONCURRENT_SWEEP ON CACHE BOOL "")
set(OMR_PORT_ASYNC_HANDLER ON CACHE BOOL "")
set(OMR_PORT_CAN_RESERVE_SPECIFIC_ADDRESS ON CACHE BOOL "")
set(OMR_PORT_NUMA_SUPPORT ON CACHE BOOL "")
set(OMR_THR_JLM ON CACHE BOOL "")
set(OMR_THR_YIELD_ALG ON CACHE BOOL "")
set(OMR_THR_SPIN_WAKE_CONTROL ON CACHE BOOL "")
set(OMR_THR_CUSTOM_SPIN_OPTIONS ON CACHE BOOL "")
set(OMR_NOTIFY_POLICY_CONTROL ON CACHE BOOL "")
set(OMR_THR_THREE_TIER_LOCKING ON CACHE BOOL "")
set(J9VM_OPT_MEMORY_CHECK_SUPPORT ON CACHE BOOL "")
set(J9VM_OPT_REMOTE_CONSOLE_SUPPORT ON CACHE BOOL "")
set(J9VM_GC_VLHGC ON CACHE BOOL "")


set(J9VM_MODULE_JEXTRACTNATIVES ON CACHE BOOL "")

set(J9VM_MODULE_ALGORITHM_TEST ON CACHE BOOL "")
set(J9VM_MODULE_BCUTIL ON CACHE BOOL "")
set(J9VM_MODULE_BCVERIFY ON CACHE BOOL "")
set(J9VM_MODULE_CALLCONV ON CACHE BOOL "")
set(J9VM_MODULE_CASSUME ON CACHE BOOL "")
set(J9VM_MODULE_CFDUMPER ON CACHE BOOL "")
set(J9VM_MODULE_CODEGEN_COMMON ON CACHE BOOL "")
set(J9VM_MODULE_CODEGEN_IA32 ON CACHE BOOL "")
set(J9VM_MODULE_CODEGEN_ILGEN ON CACHE BOOL "")
set(J9VM_MODULE_CODEGEN_OPT ON CACHE BOOL "")
set(J9VM_MODULE_CODERT_COMMON ON CACHE BOOL "")
set(J9VM_MODULE_CODERT_IA32 ON CACHE BOOL "")
set(J9VM_MODULE_CODERT_VM ON CACHE BOOL "")
set(J9VM_MODULE_CPO_COMMON ON CACHE BOOL "")
set(J9VM_MODULE_CPO_CONTROLLER ON CACHE BOOL "")
set(J9VM_MODULE_DBGEXT ON CACHE BOOL "")
set(J9VM_MODULE_DBGINFOSERV ON CACHE BOOL "")
set(J9VM_MODULE_DDR OFF CACHE BOOL "")
set(J9VM_MODULE_EXE ON CACHE BOOL "")
set(J9VM_MODULE_EXELIB ON CACHE BOOL "")


#<flag id="module_exe.j9" value="true"/>

set(J9VM_MODULE_GC ON CACHE BOOL "")
set(J9VM_MODULE_GC_API ON CACHE BOOL "")
set(J9VM_MODULE_GC_BASE ON CACHE BOOL "")
set(J9VM_MODULE_GC_CHECK ON CACHE BOOL "")
set(J9VM_MODULE_GC_COMMON OFF CACHE BOOL "")
set(J9VM_MODULE_GC_MODRON_BASE ON CACHE BOOL "")
set(J9VM_MODULE_GC_MODRON_EPROF ON CACHE BOOL "")
set(J9VM_MODULE_GC_MODRON_STANDARD ON CACHE BOOL "")
set(J9VM_MODULE_GC_MODRON_STARTUP ON CACHE BOOL "")
set(J9VM_MODULE_GC_REALTIME ON CACHE BOOL "")
set(J9VM_MODULE_GC_STACCATO ON CACHE BOOL "")
set(J9VM_MODULE_GC_STATS ON CACHE BOOL "")
set(J9VM_MODULE_GC_STRUCTS ON CACHE BOOL "")
set(J9VM_MODULE_GC_TRACE ON CACHE BOOL "")
set(J9VM_MODULE_GC_UTIL ON CACHE BOOL "")
set(J9VM_MODULE_GC_UTIL ON CACHE BOOL "")
set(J9VM_MODULE_GCCHK ON CACHE BOOL "")
set(J9VM_MODULE_GDB ON CACHE BOOL "")
set(J9VM_MODULE_GDB_PLUGIN ON CACHE BOOL "")
set(J9VM_MODULE_GPTEST ON CACHE BOOL "")
set(J9VM_MODULE_J9VM ON CACHE BOOL "")
set(J9VM_MODULE_J9VMTEST ON CACHE BOOL "")


#<flag id="module_jcl.profile_scar" value="true"/>
#<flag id="module_jcl.scar" value="true"/>

set(J9VM_MODULE_JEXTRACTNATIVES ON CACHE BOOL "")

set(J9VM_MODULE_JIT_COMMON ON CACHE BOOL "")
set(J9VM_MODULE_JIT_IA32 ON CACHE BOOL "")
set(J9VM_MODULE_JIT_VM ON CACHE BOOL "")
set(J9VM_MODULE_JITDEBUG_COMMON ON CACHE BOOL "")
set(J9VM_MODULE_JITRT_COMMON ON CACHE BOOL "")
set(J9VM_MODULE_JITRT_IA32 ON CACHE BOOL "")
set(J9VM_MODULE_JNIARGTESTS ON CACHE BOOL "")
set(J9VM_MODULE_JNICHK ON CACHE BOOL "")
set(J9VM_MODULE_JNIINV ON CACHE BOOL "")
set(J9VM_MODULE_JNITEST ON CACHE BOOL "")
set(J9VM_MODULE_JVMTI ON CACHE BOOL "")
set(J9VM_MODULE_JVMTITST ON CACHE BOOL "")
set(J9VM_MODULE_LIFECYCLE_TESTS ON CACHE BOOL "")
set(J9VM_MODULE_MASM2GAS ON CACHE BOOL "")
set(J9VM_MODULE_MVMTEST ON CACHE BOOL "")
set(J9VM_MODULE_PORTTEST ON CACHE BOOL "")
set(J9VM_MODULE_RASDUMP ON CACHE BOOL "")
set(J9VM_MODULE_RASTRACE ON CACHE BOOL "")
set(J9VM_MODULE_SHARED ON CACHE BOOL "")
set(J9VM_MODULE_SHARED_COMMON ON CACHE BOOL "")
set(J9VM_MODULE_SHARED_TEST ON CACHE BOOL "")
set(J9VM_MODULE_SHARED_UTIL ON CACHE BOOL "")
set(J9VM_MODULE_UTE ON CACHE BOOL "")
set(J9VM_MODULE_UTETEST ON CACHE BOOL "")
set(J9VM_MODULE_VERBOSE ON CACHE BOOL "")
set(J9VM_MODULE_VMALL ON CACHE BOOL "")
set(J9VM_MODULE_ZIP ON CACHE BOOL "")
set(J9VM_MODULE_ZLIB ON CACHE BOOL "")

set(CMAKE_C_COMPILER cc CACHE STRING "")

set(CMAKE_CXX_COMPILER c++ CACHE STRING "")

#for weird platforms where we compile C with the C++ compiler
set(CMAKE_C_CREATE_SHARED_LIBRARY "cc <CMAKE_SHARED_LIBRARY_C_FLAGS> <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> <CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS> <SONAME_FLAG><TARGET_SONAME> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>" CACHE STRING "")

#Prefer the C linker
set(CMAKE_C_LINKER_PREFERENCE 10 CACHE STRING "")
set(CMAKE_CXX_LINKER_PREFERENCE 1 CACHE STRING "")
