set(CMAKE_J9VM_C_ALT_DEFINE_FLAG -D)
set(CMAKE_INCLUDE_FLAG_J9VM_C_ALT -I)
set(CMAKE_J9VM_C_ALT_OUTPUT_EXTENSION .o)
set(CMAKE_J9VM_C_ALT_COMPILE_OBJECT "<CMAKE_J9VM_C_ALT_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT>   -c <SOURCE>")
